### ISSUE TITLE
In a small town the population is p0 = 1000 at the beginning of a year. The population regularly increases by 2 percent per year and moreover 50 new inhabitants per year come to live in the town. How many years does the town need to see its population greater or equal to p = 1200 inhabitants? 

### ISSUE THREAD

**Issue by karandtu** [alainrk/javaChallenges#1]
Is this approach correct to find the passed test solutions?

function nbYear(p0, percent, aug, p)
{
  population = p0;
 
 percent = percent/100;
 
 var year = 0;
 
 for(i = 0 ; population <= p ; i++){
 
   population = population + (population * percent) + aug;
    year++;
 
 }
  
return year;
}

nbYear(1000, 2, 50, 1200);

**Comment by alainrk** [comment]
Yep, it seems correct @karandtu

**Comment by karandtu** [comment]
Thanks @alainrk
